trigger:
  branches:
    include:
      - main
  paths:
    include:
      - function_api/**
      - function_api.yml

pool:
  name: Default
  demands:
    - agent.name -equals SKYETEC-8748

variables:
  azureSubscription: FireSafe Poc Devops
  resourceGroupName: "firesafe-poc-devops-rg"
  appName: "firesafe-poc-devops-func"
  packagePath: "$(System.DefaultWorkingDirectory)/function_api"

jobs:
  - job: build
    displayName: "Build Azure Function"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "20.x"
        displayName: "Install Node.js"

      - script: |
          sudo apt-get update
          sudo apt-get install -y zip
        displayName: "Install zip utility"

      - script: |
          cd function_api
          npm install
          npm run build
        displayName: "Install dependencies and build"

      - task: ArchiveFiles@2
        displayName: "Archive files"
        inputs:
          rootFolderOrFile: "$(packagePath)"
          includeRootFolder: false
          archiveFile: "$(packagePath)/build$(Build.BuildId).zip"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(packagePath)/build$(Build.BuildId).zip"
          artifactName: "drop"

  - job: deploy
    displayName: "Deploy Azure Function"
    dependsOn: build
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: drop
          path: "$(Build.ArtifactStagingDirectory)"
      - task: AzureFunctionApp@2
        inputs:
          azureSubscription: "$(azureSubscription)"
          appName: "$(appName)"
          package: $(System.ArtifactsDirectory)/**/*.zip
