backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  api_root: https://purple-river-079ed8c03.5.azurestaticapps.net/api
  #base_url: https://purple-river-079ed8c03.5.azurestaticapps.net
  #auth_endpoint: api
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
