local_backend: true
backend:
  name: git-gateway
media_folder: /public/media
public_folder: /media
i18n:
  structure: multiple_files
  locales: [en, no, dk]
  default_locale: en
collections:
  - name: "norwaySolutions"
    label: "Norway solutions"
    label_singular: "solution"
    create: true
    folder: "content/solutions/norway"
    slug: "{{fields.uuid}}"
    i18n: { structure: multiple_files, locales: [no, en], default_locale: no }
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "UUID", name: "uuid", widget: "hidden", i18n: duplicate }
      - { label: "PDF-file", name: "pdfUrl", widget: "file", i18n: true }
      - { label: "PDF-page", name: "pdfPage", widget: "number", i18n: true }
      - {
          label: "Construction",
          name: "construction",
          widget: "relation",
          collection: "constructions",
          display_fields: ["title"],
          search_fields: ["title"],
          value_field: "uuid",
          i18n: duplicate,
        }
      - {
          label: "Construction type",
          name: "constructionType",
          widget: "relation",
          collection: "constructionTypes",
          display_fields: ["title"],
          search_fields: ["title"],
          value_field: "uuid",
          i18n: duplicate,
        }
      - {
          label: "Fire resistance class",
          name: "fireResistanceClass",
          widget: "relation",
          collection: "fireResistanceClasses",
          display_fields: ["title"],
          search_fields: ["title"],
          value_field: "uuid",
          i18n: duplicate,
        }
      - {
          label: "Number of penetrations",
          name: "numberOfPenetrations",
          widget: "relation",
          collection: "numberOfPenetrations",
          display_fields: ["title"],
          search_fields: ["title"],
          value_field: "uuid",
          i18n: duplicate,
        }
      - {
          label: "Penetration group",
          name: "penetrationGroup",
          widget: "relation",
          collection: "penetrationGroups",
          display_fields: ["title"],
          search_fields: ["title"],
          value_field: "uuid",
          i18n: duplicate,
        }
      - {
          label: "Penetration type",
          name: "penetrationType",
          widget: "relation",
          collection: "penetrationTypes",
          display_fields: ["title"],
          search_fields: ["title"],
          value_field: "uuid",
          i18n: duplicate,
          required: false,
        }
      - {
          label: "Insulation type",
          name: "insulationType",
          widget: "relation",
          collection: "insulationTypes",
          display_fields: ["title"],
          search_fields: ["title"],
          value_field: "uuid",
          i18n: duplicate,
          required: false,
        }
      - {
          label: "Dimensions",
          name: "dimensions",
          widget: "relation",
          collection: "dimensions",
          display_fields: ["title"],
          search_fields: ["title"],
          value_field: "uuid",
          i18n: duplicate,
          required: false,
        }
      - {
          label: "Product",
          name: "product",
          widget: "relation",
          collection: "products",
          display_fields: ["title"],
          search_fields: ["title"],
          value_field: "uuid",
          i18n: duplicate,
        }
  - name: constructions
    folder: content/options/constructions
    label: Constructions
    label_singular: constructions
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "UUID", name: "uuid", widget: "hidden" }
      - { label: "Icon", name: "iconUrl", widget: "image", required: false }
  - name: constructionTypes
    folder: content/options/construction-types
    label: Construction types
    label_singular: construction type
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "UUID", name: "uuid", widget: "hidden" }
      - { label: "Icon", name: "iconUrl", widget: "image", required: false }
  - name: fireResistanceClasses
    folder: content/options/fire-resistance-classes
    label: Fire resistance classes
    label_singular: fire resistance class
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "UUID", name: "uuid", widget: "hidden" }
      - { label: "Icon", name: "iconUrl", widget: "image", required: false }
  - name: numberOfPenetrations
    folder: content/options/number-of-penetrations
    label: Number of penetrations
    label_singular: number of penetrations
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "UUID", name: "uuid", widget: "hidden" }
      - { label: "Icon", name: "iconUrl", widget: "image", required: false }
  - name: penetrationGroups
    folder: content/options/penetration-groups
    label: Penetration groups
    label_singular: penetration group
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "UUID", name: "uuid", widget: "hidden" }
      - { label: "Icon", name: "iconUrl", widget: "image", required: false }
  - name: penetrationTypes
    folder: content/options/penetration-types
    label: Penetration types
    label_singular: penetration type
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "UUID", name: "uuid", widget: "hidden" }
      - { label: "Icon", name: "iconUrl", widget: "image", required: false }
  - name: insulationTypes
    folder: content/options/insulation-types
    label: Insulation types
    label_singular: insulation type
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "UUID", name: "uuid", widget: "hidden" }
      - { label: "Icon", name: "iconUrl", widget: "image", required: false }
  - name: dimensions
    folder: content/options/dimensions
    label: Dimensions
    label_singular: dimension
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "UUID", name: "uuid", widget: "hidden" }
      - { label: "Icon", name: "iconUrl", widget: "image", required: false }
  - name: products
    folder: content/options/products
    label: Products
    label_singular: product
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "UUID", name: "uuid", widget: "hidden" }
      - { label: "Icon", name: "iconUrl", widget: "image", required: false }
