backend:
  name: github
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://oauthcms.azurewebsites.net
  repo: SkyeTec-no/firesafe-poc
media_folder: public/img
public_folder: img
i18n:
  structure: multiple_files
  locales: [en, no, dk]
  default_locale: en
collections:
  - name: "norwaySolutions"
    label: "Norway solutions"
    label_singular: "solution"
    create: true
    folder: "content/solutions/norway"
    slug: "{{fields.uuid}}"
    i18n: { structure: multiple_files, locales: [no, en], default_locale: no }
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "UUID", name: "uuid", widget: "hidden", i18n: duplicate }
      - {
          label: "PDF-file",
          name: "pdfUrl",
          widget: "file",
          media_folder: "public/pdf",
          public_folder: "/pdf",
          i18n: true,
        }
      - { label: "PDF-page", name: "pdfPage", widget: "number", i18n: true }
      - {
          label: "Construction",
          name: "construction",
          widget: "relation",
          collection: "constructions",
          search_fields: ["title"],
          value_field: "title",
          i18n: duplicate,
        }
      - {
          label: "Construction type",
          name: "constructionType",
          widget: "relation",
          collection: "constructionTypes",
          search_fields: ["title"],
          value_field: "title",
          i18n: duplicate,
        }
      - {
          label: "Fire resistance class",
          name: "fireResistanceClass",
          widget: "relation",
          collection: "fireResistanceClasses",
          search_fields: ["title"],
          value_field: "title",
          i18n: duplicate,
        }
      - {
          label: "Number of penetrations",
          name: "numberOfPenetrations",
          widget: "relation",
          collection: "numberOfPenetrations",
          search_fields: ["title"],
          value_field: "title",
          i18n: duplicate,
        }
      - {
          label: "Penetration group",
          name: "penetrationGroup",
          widget: "relation",
          collection: "penetrationGroups",
          search_fields: ["title"],
          value_field: "title",
          i18n: duplicate,
        }
      - {
          label: "Penetration type",
          name: "penetrationType",
          widget: "relation",
          collection: "penetrationTypes",
          search_fields: ["title"],
          value_field: "title",
          i18n: duplicate,
          required: false,
        }
      - {
          label: "Insulation type",
          name: "insulationType",
          widget: "relation",
          collection: "insulationTypes",
          search_fields: ["title"],
          value_field: "title",
          i18n: duplicate,
          required: false,
        }
      - {
          label: "Dimensions",
          name: "dimensions",
          widget: "relation",
          collection: "dimensions",
          search_fields: ["title"],
          value_field: "title",
          i18n: duplicate,
          required: false,
        }
      - {
          label: "Product",
          name: "product",
          widget: "relation",
          collection: "products",
          search_fields: ["title"],
          value_field: "title",
          i18n: duplicate,
        }
  - name: constructions
    folder: content/options/constructions
    label: Constructions
    label_singular: constructions
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
  - name: constructionTypes
    folder: content/options/construction-types
    label: Construction types
    label_singular: construction type
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
  - name: fireResistanceClasses
    folder: content/options/fire-resistance-classes
    label: Fire resistance classes
    label_singular: fire resistance class
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
  - name: numberOfPenetrations
    folder: content/options/number-of-penetrations
    label: Number of penetrations
    label_singular: number of penetrations
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
  - name: penetrationGroups
    folder: content/options/penetration-groups
    label: Penetration groups
    label_singular: penetration group
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
  - name: penetrationTypes
    folder: content/options/penetration-types
    label: Penetration types
    label_singular: penetration type
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
  - name: insulationTypes
    folder: content/options/insulation-types
    label: Insulation types
    label_singular: insulation type
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
  - name: dimensions
    folder: content/options/dimensions
    label: Dimensions
    label_singular: dimension
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
  - name: products
    folder: content/options/products
    label: Products
    label_singular: product
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
